In [3]:
import numpy as np
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [4]:
type(a)

numpy.ndarray

In [5]:
b = np.zeros(2)
b


array([0., 0.])

In [7]:
c = np.zeros(3)
c

array([0., 0., 0.])

In [9]:
d = np.empty(5)
d

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [12]:
# multi dimensional array
mdarray = np.array([[1,2,3], [4,5,6], [7, 8, 9]])
mdarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
mdarray[0]


array([1, 2, 3])

In [16]:
mdarray[1:3]


array([[4, 5, 6],
       [7, 8, 9]])

In [17]:
mdarray[0][0]


1

In [19]:
# creating array with range of elements
e = np.arange(6)
e

array([0, 1, 2, 3, 4, 5])

In [20]:
f = np.arange(2, 20)
f


array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [21]:
# steps in aRange
g = np.arange(2, 20, 2)
g


array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [22]:
# linearly spaced numbers array
h = np.linspace(0, 10, num=5)
h


array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [31]:
i = np.linspace(0, 20, num=11)
i

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

In [32]:
j = np.ones(5, dtype=np.int8)
j


array([1, 1, 1, 1, 1], dtype=int8)

In [33]:
k = np.ones(10, dtype=np.float16)
k


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float16)

## 2-D arrays


In [34]:
# create a 3 by 4 matrix 2-D array
l = np.zeros((3,4))
l

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [35]:
m = np.ones((4,5))
m


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [36]:
n = np.empty((3,5))
n


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

## 3-D Array


In [41]:
simple_array = np.arange(24)
simple_array


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [46]:
array3d = simple_array.reshape(2, 3, 4)
array3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])