# Numpy Practice Session


In [1]:
# if numpy is not already installed, run this command first
# pip install numpy


In [2]:
import numpy as np


## Craeting an array using numpy


In [3]:
fast_food = np.array(["Pakorha", "Samosa",  "Raita"])
fast_food


array(['Pakorha', 'Samosa', 'Raita'], dtype='<U7')

In [4]:
price = np.array([5,6,7])
price


array([5, 6, 7])

In [5]:
type(price)


numpy.ndarray

In [6]:
type(fast_food)


numpy.ndarray

In [7]:
len(fast_food)


3

In [8]:
len(price)


3

In [9]:
# Indexing
price[2]


7

In [10]:
fast_food[1]


'Samosa'

In [11]:
price


array([5, 6, 7])

In [12]:
# cumulative sum
price.cumsum()


array([ 5, 11, 18], dtype=int32)

In [13]:
# Zeros
np.zeros(6)


array([0., 0., 0., 0., 0., 0.])

In [14]:
np.ones(5)


array([1., 1., 1., 1., 1.])

In [15]:
# empty, unlike zeros, does not set the array values to zero, and may therefore be marginally faster. On the other hand, it requires the user to manually set all the values in the array, and should be used with caution.
np.empty(5)


array([1., 1., 1., 1., 1.])

In [16]:
np.arange(10)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.empty(5, dtype=np.int8)


array([1, 1, 1, 1, 1], dtype=int8)

In [18]:
np.empty([2, 2])


array([[2.05833592e-312, 2.35541533e-312],
       [2.05833592e-312, 1.08858384e-311]])

In [19]:
np.empty([2,2], dtype=np.float16)


array([[0.00e+00, 0.00e+00],
       [3.06e-05, 0.00e+00]], dtype=float16)

In [20]:
np.arange(10)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
np.arange(2,20)


array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [22]:
# specifying range with interval
np.arange(13, 23, 2)


array([13, 15, 17, 19, 21])

In [23]:
np.arange(5, 55, 5)


array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [24]:
np.linspace(1, 100, num=10)


array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [25]:
np.ones(50, dtype=np.float64)


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

 ## Array functions


In [26]:
a = np.array([10, 12, 15, 2, 4, 6, 100, 320, 0.5, 10.5])
a

array([ 10. ,  12. ,  15. ,   2. ,   4. ,   6. , 100. , 320. ,   0.5,
        10.5])

In [27]:
a.sort()
a

array([  0.5,   2. ,   4. ,   6. ,  10. ,  10.5,  12. ,  15. , 100. ,
       320. ])

In [28]:
b = np.array([10.2, 3.4, 53.6, 91.2, 40.4])
b

array([10.2,  3.4, 53.6, 91.2, 40.4])

In [29]:
# remember to pass the arrays inside parenthesis
c = np.concatenate((a,b))
c

array([  0.5,   2. ,   4. ,   6. ,  10. ,  10.5,  12. ,  15. , 100. ,
       320. ,  10.2,   3.4,  53.6,  91.2,  40.4])

In [30]:
c.sort()
c


array([  0.5,   2. ,   3.4,   4. ,   6. ,  10. ,  10.2,  10.5,  12. ,
        15. ,  40.4,  53.6,  91.2, 100. , 320. ])

In [31]:
d = np.array([[1,2,3,4,5], [5,4,3,2,1]])
d


array([[1, 2, 3, 4, 5],
       [5, 4, 3, 2, 1]])

In [32]:
e = np.array([[1,2], [3,4]])
e


array([[1, 2],
       [3, 4]])

In [33]:
f = np.concatenate((d,e))
f


ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 5 and the array at index 1 has size 2

In [34]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6], [7,8]])
arr1


array([[1, 2],
       [3, 4]])

In [35]:
arr2


array([[5, 6],
       [7, 8]])

In [36]:
np.concatenate((arr1, arr2), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [37]:
np.concatenate((arr1, arr2), axis=1)


array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [39]:
# shaping an array into 3d array
simple_array = np.arange(24)
array_3d = simple_array.reshape(3,2,4)
array_3d


array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [41]:
# finding the number of dimensions of an array
array_3d.ndim


3

In [43]:
arr4 = np.array([
    [5,6,7],
    [8,9,10],
    [10,11, 12]
])
arr4

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [10, 11, 12]])

In [44]:
arr4.ndim


2

In [45]:
arr4.size


9

In [47]:
# size = number of elements
array_3d.size


24

In [49]:
array_3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [48]:
array_3d.shape


(3, 2, 4)

In [57]:
arr5 = np.arange(9)
arr5

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [59]:
reshaped_array = arr5.reshape(3,3)
reshaped_array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [66]:
# arr5.reshape((3,3), shape=(1,9), order="C")
arr5.reshape(1,9)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [70]:
np.reshape(arr5, newshape=(1,9), order="C")


array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [71]:
np.reshape(arr5, newshape=(9,1))


array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [74]:
f = np.reshape(arr5, newshape=(1,3,3))
f

array([[[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]])

In [75]:
f.ndim


3

In [76]:
np.reshape(arr5, newshape=(3,1,3))


array([[[0, 1, 2]],

       [[3, 4, 5]],

       [[6, 7, 8]]])

In [77]:
np.reshape(arr5, newshape=(3,3,1))


array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]],

       [[6],
        [7],
        [8]]])

In [78]:
np.reshape(arr5, newshape=(3, 1, 3))


array([[[0, 1, 2]],

       [[3, 4, 5]],

       [[6, 7, 8]]])

In [79]:
np.reshape(arr5, newshape=(1, 3,3))


array([[[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]])

In [80]:
t = np.array([
    [
        [0,1,2],
        [3,4,5],
        [6,7,8]
    ]
])
t


array([[[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]])

In [84]:
# converting 1-D to 2-D array
arr6 = np.arange(1,10)
arr6

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [85]:
arr7 = a[np.newaxis, 0:len(arr6)]
arr7


array([[  0.5,   2. ,   4. ,   6. ,  10. ,  10.5,  12. ,  15. , 100. ]])

In [86]:
arr7.shape


(1, 9)

In [91]:
print(arr6.shape)
arr6.ndim

(9,)


1

In [92]:
print(arr7.shape)
arr7.ndim


(1, 9)


2

In [93]:
a


array([  0.5,   2. ,   4. ,   6. ,  10. ,  10.5,  12. ,  15. , 100. ,
       320. ])

In [94]:
ar1 = np.arange(6, 60, 6)
ar1


array([ 6, 12, 18, 24, 30, 36, 42, 48, 54])

In [95]:
ar1.sum()


270

In [96]:
ar1.mean()


30.0

In [98]:
ar1/6


array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [100]:
ar1.ndim


1

In [102]:
array_3d.shape


(3, 2, 4)

In [ ]:
array_3d
