# Learning Pandas With Dr. Ammar Tufail

In [76]:
import numpy as np
# import libraries
import pandas as pd

In [77]:
# Object Creation
sample_series = pd.Series([1, 3, np.nan, 5, 7, 8, 9])
sample_series

0    1.0
1    3.0
2    NaN
3    5.0
4    7.0
5    8.0
6    9.0
dtype: float64

In [78]:
# Creating date range by pandas
dates = pd.date_range("20220101", periods=20)
dates

DatetimeIndex(['2022-01-01', '2022-01-02', '2022-01-03', '2022-01-04',
               '2022-01-05', '2022-01-06', '2022-01-07', '2022-01-08',
               '2022-01-09', '2022-01-10', '2022-01-11', '2022-01-12',
               '2022-01-13', '2022-01-14', '2022-01-15', '2022-01-16',
               '2022-01-17', '2022-01-18', '2022-01-19', '2022-01-20'],
              dtype='datetime64[ns]', freq='D')

In [79]:
# Create a 2 dimensional array by using numpy random.randn function
random_array = np.random.randn(20, 4)
random_array

array([[-1.06301134,  0.46089624, -1.7789289 ,  0.84887228],
       [-0.57892716,  0.95001586, -0.62506204, -1.28478935],
       [ 1.84199174, -0.24165677, -1.03196933,  0.67833603],
       [-0.75409569,  1.33108553,  0.9652746 , -0.74313757],
       [ 1.00309225, -1.28559331,  0.19952747, -1.1490591 ],
       [-0.39305088, -0.57199408,  0.83360896, -0.12616482],
       [ 0.08352278, -0.26640556,  0.81618058,  1.38926521],
       [ 0.0192892 , -1.89235129, -1.67272372,  0.46975966],
       [-0.27350248,  0.52018485, -0.84996835,  1.05416889],
       [-1.10967097,  1.33774475,  0.34733211, -0.51797207],
       [-1.26363632,  1.04786057,  0.78790717,  0.71313271],
       [-1.37631508,  0.96965598,  1.44984103, -0.6429145 ],
       [ 1.81216367, -2.70219848,  1.17294909, -0.38529561],
       [-0.32859365,  0.37164506,  1.02751473, -0.86967547],
       [ 0.01101568,  0.08884473,  0.91504808, -0.86505108],
       [ 1.13889745, -0.65602376,  1.38234912, -0.19966093],
       [-2.33922004,  2.

In [80]:
# Creating DataFrame
# sample_data_frame = pd.DataFrame(random_array, index=dates, columns="abcd")
# TypeError: Index(...) must be called with a collection of some kind, 'abcd' was passed

sample_data_frame = pd.DataFrame(random_array, index=dates, columns=list("ABCD"))
sample_data_frame

A         B         C         D
2022-01-01 -1.063011  0.460896 -1.778929  0.848872
2022-01-02 -0.578927  0.950016 -0.625062 -1.284789
2022-01-03  1.841992 -0.241657 -1.031969  0.678336
2022-01-04 -0.754096  1.331086  0.965275 -0.743138
2022-01-05  1.003092 -1.285593  0.199527 -1.149059
2022-01-06 -0.393051 -0.571994  0.833609 -0.126165
2022-01-07  0.083523 -0.266406  0.816181  1.389265
2022-01-08  0.019289 -1.892351 -1.672724  0.469760
2022-01-09 -0.273502  0.520185 -0.849968  1.054169
2022-01-10 -1.109671  1.337745  0.347332 -0.517972
2022-01-11 -1.263636  1.047861  0.787907  0.713133
2022-01-12 -1.376315  0.969656  1.449841 -0.642914
2022-01-13  1.812164 -2.702198  1.172949 -0.385296
2022-01-14 -0.328594  0.371645  1.027515 -0.869675
2022-01-15  0.011016  0.088845  0.915048 -0.865051
2022-01-16  1.138897 -0.656024  1.382349 -0.199661
2022-01-17 -2.339220  2.036712  0.873930 -0.072603
2022-01-18 -1.696726 -0.352158 -0.218300  1.905248
2022-01-19  0.286306  0.062278 -0.378840  0.406134
2022-01-20 -0.611623  0.985538  0.924371  1.067879

In [81]:
# Creating Data Frame using pandas
data_frame2 = pd.DataFrame(
    {
        "A": 1.0,
        "B": pd.Timestamp("20130102"),
        "C": pd.Series(3, index=list(range(5)), dtype=np.float32),
        "D": np.array([3] * 5, dtype="int32"),
        "E": pd.Categorical(["girl", "woman", "girl", "woman", "girl"]),
        "F": "females"
    }
)

data_frame2

A          B    C  D      E        F
0  1.0 2013-01-02  3.0  3   girl  females
1  1.0 2013-01-02  3.0  3  woman  females
2  1.0 2013-01-02  3.0  3   girl  females
3  1.0 2013-01-02  3.0  3  woman  females
4  1.0 2013-01-02  3.0  3   girl  females

In [82]:
data_frame2.dtypes

A           float64
B    datetime64[ns]
C           float32
D             int32
E          category
F            object
dtype: object

In [83]:
data_frame2.head()

A          B    C  D      E        F
0  1.0 2013-01-02  3.0  3   girl  females
1  1.0 2013-01-02  3.0  3  woman  females
2  1.0 2013-01-02  3.0  3   girl  females
3  1.0 2013-01-02  3.0  3  woman  females
4  1.0 2013-01-02  3.0  3   girl  females

In [84]:
data_frame2.tail(2)

A          B    C  D      E        F
3  1.0 2013-01-02  3.0  3  woman  females
4  1.0 2013-01-02  3.0  3   girl  females

In [85]:
# Creating Data Frame using pandas
data_frame3 = pd.DataFrame(
    {
        "A": 1.0,
        "B": dates[:5],
        "C": pd.Series(3, index=list(range(5)), dtype=np.float32),
        "D": np.array([3] * 5, dtype="int32"),
        "E": pd.Categorical(["girl", "woman", "girl", "woman", "girl"]),
        "F": "females"
    }
)

data_frame3

A          B    C  D      E        F
0  1.0 2022-01-01  3.0  3   girl  females
1  1.0 2022-01-02  3.0  3  woman  females
2  1.0 2022-01-03  3.0  3   girl  females
3  1.0 2022-01-04  3.0  3  woman  females
4  1.0 2022-01-05  3.0  3   girl  females

In [86]:
data_frame3.head(2)

A          B    C  D      E        F
0  1.0 2022-01-01  3.0  3   girl  females
1  1.0 2022-01-02  3.0  3  woman  females

In [87]:
data_frame3.tail(2)

A          B    C  D      E        F
3  1.0 2022-01-04  3.0  3  woman  females
4  1.0 2022-01-05  3.0  3   girl  females

In [88]:
sample_data_frame.index

DatetimeIndex(['2022-01-01', '2022-01-02', '2022-01-03', '2022-01-04',
               '2022-01-05', '2022-01-06', '2022-01-07', '2022-01-08',
               '2022-01-09', '2022-01-10', '2022-01-11', '2022-01-12',
               '2022-01-13', '2022-01-14', '2022-01-15', '2022-01-16',
               '2022-01-17', '2022-01-18', '2022-01-19', '2022-01-20'],
              dtype='datetime64[ns]', freq='D')

In [89]:
data_frame3.index

Int64Index([0, 1, 2, 3, 4], dtype='int64')

In [90]:
sample_data_frame.to_numpy()

array([[-1.06301134,  0.46089624, -1.7789289 ,  0.84887228],
       [-0.57892716,  0.95001586, -0.62506204, -1.28478935],
       [ 1.84199174, -0.24165677, -1.03196933,  0.67833603],
       [-0.75409569,  1.33108553,  0.9652746 , -0.74313757],
       [ 1.00309225, -1.28559331,  0.19952747, -1.1490591 ],
       [-0.39305088, -0.57199408,  0.83360896, -0.12616482],
       [ 0.08352278, -0.26640556,  0.81618058,  1.38926521],
       [ 0.0192892 , -1.89235129, -1.67272372,  0.46975966],
       [-0.27350248,  0.52018485, -0.84996835,  1.05416889],
       [-1.10967097,  1.33774475,  0.34733211, -0.51797207],
       [-1.26363632,  1.04786057,  0.78790717,  0.71313271],
       [-1.37631508,  0.96965598,  1.44984103, -0.6429145 ],
       [ 1.81216367, -2.70219848,  1.17294909, -0.38529561],
       [-0.32859365,  0.37164506,  1.02751473, -0.86967547],
       [ 0.01101568,  0.08884473,  0.91504808, -0.86505108],
       [ 1.13889745, -0.65602376,  1.38234912, -0.19966093],
       [-2.33922004,  2.

In [91]:
sample_data_frame

A         B         C         D
2022-01-01 -1.063011  0.460896 -1.778929  0.848872
2022-01-02 -0.578927  0.950016 -0.625062 -1.284789
2022-01-03  1.841992 -0.241657 -1.031969  0.678336
2022-01-04 -0.754096  1.331086  0.965275 -0.743138
2022-01-05  1.003092 -1.285593  0.199527 -1.149059
2022-01-06 -0.393051 -0.571994  0.833609 -0.126165
2022-01-07  0.083523 -0.266406  0.816181  1.389265
2022-01-08  0.019289 -1.892351 -1.672724  0.469760
2022-01-09 -0.273502  0.520185 -0.849968  1.054169
2022-01-10 -1.109671  1.337745  0.347332 -0.517972
2022-01-11 -1.263636  1.047861  0.787907  0.713133
2022-01-12 -1.376315  0.969656  1.449841 -0.642914
2022-01-13  1.812164 -2.702198  1.172949 -0.385296
2022-01-14 -0.328594  0.371645  1.027515 -0.869675
2022-01-15  0.011016  0.088845  0.915048 -0.865051
2022-01-16  1.138897 -0.656024  1.382349 -0.199661
2022-01-17 -2.339220  2.036712  0.873930 -0.072603
2022-01-18 -1.696726 -0.352158 -0.218300  1.905248
2022-01-19  0.286306  0.062278 -0.378840  0.406134
2022-01-20 -0.611623  0.985538  0.924371  1.067879

In [92]:
data_frame3.to_numpy()

array([[1.0, Timestamp('2022-01-01 00:00:00'), 3.0, 3, 'girl', 'females'],
       [1.0, Timestamp('2022-01-02 00:00:00'), 3.0, 3, 'woman',
        'females'],
       [1.0, Timestamp('2022-01-03 00:00:00'), 3.0, 3, 'girl', 'females'],
       [1.0, Timestamp('2022-01-04 00:00:00'), 3.0, 3, 'woman',
        'females'],
       [1.0, Timestamp('2022-01-05 00:00:00'), 3.0, 3, 'girl', 'females']],
      dtype=object)

In [93]:
sample_data_frame.describe()

A          B          C          D
count  20.000000  20.000000  20.000000  20.000000
mean   -0.279605   0.109704   0.257002   0.083824
std     1.107971   1.159863   0.999605   0.908008
min    -2.339220  -2.702198  -1.778929  -1.284789
25%    -1.074676  -0.407117  -0.440396  -0.667970
50%    -0.360822   0.230245   0.802044  -0.099384
75%     0.134219   0.973626   0.934597   0.747068
max     1.841992   2.036712   1.449841   1.905248

In [94]:
# Pandas DataFrame: transpose(); T is not callable
t = sample_data_frame.T
t

2022-01-01  2022-01-02  2022-01-03  2022-01-04  2022-01-05  2022-01-06  \
A   -1.063011   -0.578927    1.841992   -0.754096    1.003092   -0.393051   
B    0.460896    0.950016   -0.241657    1.331086   -1.285593   -0.571994   
C   -1.778929   -0.625062   -1.031969    0.965275    0.199527    0.833609   
D    0.848872   -1.284789    0.678336   -0.743138   -1.149059   -0.126165   

   2022-01-07  2022-01-08  2022-01-09  2022-01-10  2022-01-11  2022-01-12  \
A    0.083523    0.019289   -0.273502   -1.109671   -1.263636   -1.376315   
B   -0.266406   -1.892351    0.520185    1.337745    1.047861    0.969656   
C    0.816181   -1.672724   -0.849968    0.347332    0.787907    1.449841   
D    1.389265    0.469760    1.054169   -0.517972    0.713133   -0.642914   

   2022-01-13  2022-01-14  2022-01-15  2022-01-16  2022-01-17  2022-01-18  \
A    1.812164   -0.328594    0.011016    1.138897   -2.339220   -1.696726   
B   -2.702198    0.371645    0.088845   -0.656024    2.036712   -0.352158   
C    1.172949    1.027515    0.915048    1.382349    0.873930   -0.218300   
D   -0.385296   -0.869675   -0.865051   -0.199661   -0.072603    1.905248   

   2022-01-19  2022-01-20  
A    0.286306   -0.611623  
B    0.062278    0.985538  
C   -0.378840    0.924371  
D    0.406134    1.067879

In [95]:
# sample_data_frame.sort_index(axis=0, ascending=False)
# sample_data_frame.sort_values(by="D", ascending=True)

sample_data_frame[0:4].sort_index(axis=1, ascending=True)


A         B         C         D
2022-01-01 -1.063011  0.460896 -1.778929  0.848872
2022-01-02 -0.578927  0.950016 -0.625062 -1.284789
2022-01-03  1.841992 -0.241657 -1.031969  0.678336
2022-01-04 -0.754096  1.331086  0.965275 -0.743138

### What is axis in pandas DataFrame?
![IMG](https://railsware.com/blog/wp-content/uploads/2018/11/data-frame-axes.png)

In [96]:
# sample_data_frame[0:4].sort_index(axis=0, ascending=True)

In [97]:
# data selection by row
sample_data_frame[0:2]

A         B         C         D
2022-01-01 -1.063011  0.460896 -1.778929  0.848872
2022-01-02 -0.578927  0.950016 -0.625062 -1.284789

In [98]:
dates

DatetimeIndex(['2022-01-01', '2022-01-02', '2022-01-03', '2022-01-04',
               '2022-01-05', '2022-01-06', '2022-01-07', '2022-01-08',
               '2022-01-09', '2022-01-10', '2022-01-11', '2022-01-12',
               '2022-01-13', '2022-01-14', '2022-01-15', '2022-01-16',
               '2022-01-17', '2022-01-18', '2022-01-19', '2022-01-20'],
              dtype='datetime64[ns]', freq='D')

In [113]:
# selecting specific numbers to retrieve data
# data_frame3.loc[(0,3), ["A", "B", "E","F"]]
data_frame3.loc[[0,3], ["A", "B", "E","F"]]

A          B      E        F
0  1.0 2022-01-01   girl  females
3  1.0 2022-01-04  woman  females

In [116]:
# selecting a range to retrieve data
data_frame3.loc[0:2, ["A", "B", "E","F"]]

A          B      E        F
0  1.0 2022-01-01   girl  females
1  1.0 2022-01-02  woman  females
2  1.0 2022-01-03   girl  females

In [119]:
# Accessing value on a specific location
# Thing to remember that its a property and not a function, so should be used square brackets instead of round brackets
# Docs shows that this is an indexing mixin, so we can provide custom values by using square brackets
data_frame2.at[0, "E"]

'girl'

In [139]:
# Accessing value on a specific index location i.e. iloc
# data_frame2.iloc[rows, columns]
# data_frame2.iloc[0:3, 0:] # from rows 0 to 3, column 0 to all
# data_frame2.iloc[0:3, 0:1] # from rows 0 to 3, column 0 to 1
# data_frame2.iloc[0:3, 4] # from rows 0 to 3, column 4
# data_frame2.iloc[3, 4] # from rows 4 (index 3), column 5(index 4)

# data_frame2.iloc[3] # from rows 4 (index 3), columns all
# data_frame2.iloc[3, :] # from rows 4 (index 3), columns all - same as above
data_frame2.iloc[:, 4] # from all rows, columns column 5(index 4)

0     girl
1    woman
2     girl
3    woman
4     girl
Name: E, dtype: category
Categories (2, object): ['girl', 'woman']

In [143]:
# Filtering data
sample_data_frame[sample_data_frame["A"] > 1.2] # subset of data where value of a is greater than given value

A         B         C         D
2022-01-03  1.841992 -0.241657 -1.031969  0.678336
2022-01-13  1.812164 -2.702198  1.172949 -0.385296

In [144]:
sample_data_frame[sample_data_frame > 0] # subset of data where value all fields are greater than given value

A         B         C         D
2022-01-01       NaN  0.460896       NaN  0.848872
2022-01-02       NaN  0.950016       NaN       NaN
2022-01-03  1.841992       NaN       NaN  0.678336
2022-01-04       NaN  1.331086  0.965275       NaN
2022-01-05  1.003092       NaN  0.199527       NaN
2022-01-06       NaN       NaN  0.833609       NaN
2022-01-07  0.083523       NaN  0.816181  1.389265
2022-01-08  0.019289       NaN       NaN  0.469760
2022-01-09       NaN  0.520185       NaN  1.054169
2022-01-10       NaN  1.337745  0.347332       NaN
2022-01-11       NaN  1.047861  0.787907  0.713133
2022-01-12       NaN  0.969656  1.449841       NaN
2022-01-13  1.812164       NaN  1.172949       NaN
2022-01-14       NaN  0.371645  1.027515       NaN
2022-01-15  0.011016  0.088845  0.915048       NaN
2022-01-16  1.138897       NaN  1.382349       NaN
2022-01-17       NaN  2.036712  0.873930       NaN
2022-01-18       NaN       NaN       NaN  1.905248
2022-01-19  0.286306  0.062278       NaN  0.406134
2022-01-20       NaN  0.985538  0.924371  1.067879