# Learning Pandas With Dr. Ammar Tufail

In [23]:
import numpy as np
# import libraries
import pandas as pd

In [24]:
# Object Creation
sample_series = pd.Series([1, 3, np.nan, 5, 7, 8, 9])
sample_series

0    1.0
1    3.0
2    NaN
3    5.0
4    7.0
5    8.0
6    9.0
dtype: float64

In [25]:
# Creating date range by pandas
dates = pd.date_range("20220101", periods=20)
dates

DatetimeIndex(['2022-01-01', '2022-01-02', '2022-01-03', '2022-01-04',
               '2022-01-05', '2022-01-06', '2022-01-07', '2022-01-08',
               '2022-01-09', '2022-01-10', '2022-01-11', '2022-01-12',
               '2022-01-13', '2022-01-14', '2022-01-15', '2022-01-16',
               '2022-01-17', '2022-01-18', '2022-01-19', '2022-01-20'],
              dtype='datetime64[ns]', freq='D')

In [26]:
# Create a 2 dimensional array by using numpy random.randn function
random_array = np.random.randn(20, 4)
random_array

array([[ 0.55843696, -2.14358193, -1.04491573, -0.42014331],
       [-1.4551199 , -0.73062499, -1.05582721,  0.93724211],
       [-1.00357843, -2.07577779,  1.12102831, -0.91031404],
       [ 1.01627963,  0.51756165, -1.02551538, -1.85607554],
       [ 1.86848015,  2.03715226,  1.03256231,  0.19081161],
       [ 0.89607479,  0.81718761, -1.32113317,  0.10760895],
       [ 1.25362462, -0.69318376, -0.70104971,  1.87058584],
       [-0.77273973,  0.77545826, -0.24195267, -0.66355302],
       [-1.13156872,  0.02015053, -0.31700978,  1.02679149],
       [-0.45181479, -1.06728081,  0.42467161, -1.08012469],
       [-1.58934798, -1.68057148,  2.02909991, -0.04197276],
       [ 1.13222044,  1.30116685,  1.15494015,  0.83908287],
       [ 0.13845928,  0.00464934,  1.43437825,  2.62454893],
       [ 0.29670714,  0.54350232, -0.11723992, -1.688556  ],
       [-0.93584341, -1.41952935, -0.48256241, -0.78644328],
       [ 0.30844906, -0.3353353 , -1.45153386,  0.03059135],
       [ 0.66034584, -0.

In [27]:
# Creating DataFrame
# sample_data_frame = pd.DataFrame(random_array, index=dates, columns="abcd")
# TypeError: Index(...) must be called with a collection of some kind, 'abcd' was passed

sample_data_frame = pd.DataFrame(random_array, index=dates, columns=list("ABCD"))
sample_data_frame

A         B         C         D
2022-01-01  0.558437 -2.143582 -1.044916 -0.420143
2022-01-02 -1.455120 -0.730625 -1.055827  0.937242
2022-01-03 -1.003578 -2.075778  1.121028 -0.910314
2022-01-04  1.016280  0.517562 -1.025515 -1.856076
2022-01-05  1.868480  2.037152  1.032562  0.190812
2022-01-06  0.896075  0.817188 -1.321133  0.107609
2022-01-07  1.253625 -0.693184 -0.701050  1.870586
2022-01-08 -0.772740  0.775458 -0.241953 -0.663553
2022-01-09 -1.131569  0.020151 -0.317010  1.026791
2022-01-10 -0.451815 -1.067281  0.424672 -1.080125
2022-01-11 -1.589348 -1.680571  2.029100 -0.041973
2022-01-12  1.132220  1.301167  1.154940  0.839083
2022-01-13  0.138459  0.004649  1.434378  2.624549
2022-01-14  0.296707  0.543502 -0.117240 -1.688556
2022-01-15 -0.935843 -1.419529 -0.482562 -0.786443
2022-01-16  0.308449 -0.335335 -1.451534  0.030591
2022-01-17  0.660346 -0.702253 -1.291539 -1.846197
2022-01-18  0.425913 -0.014023  1.150072 -1.976980
2022-01-19  1.574675  1.252467 -1.433446  2.205638
2022-01-20  0.613642  0.859947  0.551890  0.627359

In [28]:
# Creating Data Frame using pandas
data_frame2 = pd.DataFrame(
    {
        "A": 1.0,
        "B": pd.Timestamp("20130102"),
        "C": pd.Series(3, index=list(range(5)), dtype=np.float32),
        "D": np.array([3] * 5, dtype="int32"),
        "E": pd.Categorical(["girl", "woman", "girl", "woman", "girl"]),
        "F": "females"
    }
)

data_frame2

A          B    C  D      E        F
0  1.0 2013-01-02  3.0  3   girl  females
1  1.0 2013-01-02  3.0  3  woman  females
2  1.0 2013-01-02  3.0  3   girl  females
3  1.0 2013-01-02  3.0  3  woman  females
4  1.0 2013-01-02  3.0  3   girl  females

In [29]:
data_frame2.dtypes

A           float64
B    datetime64[ns]
C           float32
D             int32
E          category
F            object
dtype: object

In [30]:
data_frame2.head()

A          B    C  D      E        F
0  1.0 2013-01-02  3.0  3   girl  females
1  1.0 2013-01-02  3.0  3  woman  females
2  1.0 2013-01-02  3.0  3   girl  females
3  1.0 2013-01-02  3.0  3  woman  females
4  1.0 2013-01-02  3.0  3   girl  females

In [31]:
data_frame2.tail(2)

A          B    C  D      E        F
3  1.0 2013-01-02  3.0  3  woman  females
4  1.0 2013-01-02  3.0  3   girl  females

In [32]:
# Creating Data Frame using pandas
data_frame3 = pd.DataFrame(
    {
        "A": 1.0,
        "B": dates[:5],
        "C": pd.Series(3, index=list(range(5)), dtype=np.float32),
        "D": np.array([3] * 5, dtype="int32"),
        "E": pd.Categorical(["girl", "woman", "girl", "woman", "girl"]),
        "F": "females"
    }
)

data_frame3

A          B    C  D      E        F
0  1.0 2022-01-01  3.0  3   girl  females
1  1.0 2022-01-02  3.0  3  woman  females
2  1.0 2022-01-03  3.0  3   girl  females
3  1.0 2022-01-04  3.0  3  woman  females
4  1.0 2022-01-05  3.0  3   girl  females

In [33]:
data_frame3.head(2)

A          B    C  D      E        F
0  1.0 2022-01-01  3.0  3   girl  females
1  1.0 2022-01-02  3.0  3  woman  females

In [34]:
data_frame3.tail(2)

A          B    C  D      E        F
3  1.0 2022-01-04  3.0  3  woman  females
4  1.0 2022-01-05  3.0  3   girl  females

In [35]:
sample_data_frame.index

DatetimeIndex(['2022-01-01', '2022-01-02', '2022-01-03', '2022-01-04',
               '2022-01-05', '2022-01-06', '2022-01-07', '2022-01-08',
               '2022-01-09', '2022-01-10', '2022-01-11', '2022-01-12',
               '2022-01-13', '2022-01-14', '2022-01-15', '2022-01-16',
               '2022-01-17', '2022-01-18', '2022-01-19', '2022-01-20'],
              dtype='datetime64[ns]', freq='D')

In [36]:
data_frame3.index

Int64Index([0, 1, 2, 3, 4], dtype='int64')

In [37]:
sample_data_frame.to_numpy()

array([[ 0.55843696, -2.14358193, -1.04491573, -0.42014331],
       [-1.4551199 , -0.73062499, -1.05582721,  0.93724211],
       [-1.00357843, -2.07577779,  1.12102831, -0.91031404],
       [ 1.01627963,  0.51756165, -1.02551538, -1.85607554],
       [ 1.86848015,  2.03715226,  1.03256231,  0.19081161],
       [ 0.89607479,  0.81718761, -1.32113317,  0.10760895],
       [ 1.25362462, -0.69318376, -0.70104971,  1.87058584],
       [-0.77273973,  0.77545826, -0.24195267, -0.66355302],
       [-1.13156872,  0.02015053, -0.31700978,  1.02679149],
       [-0.45181479, -1.06728081,  0.42467161, -1.08012469],
       [-1.58934798, -1.68057148,  2.02909991, -0.04197276],
       [ 1.13222044,  1.30116685,  1.15494015,  0.83908287],
       [ 0.13845928,  0.00464934,  1.43437825,  2.62454893],
       [ 0.29670714,  0.54350232, -0.11723992, -1.688556  ],
       [-0.93584341, -1.41952935, -0.48256241, -0.78644328],
       [ 0.30844906, -0.3353353 , -1.45153386,  0.03059135],
       [ 0.66034584, -0.

In [38]:
sample_data_frame

A         B         C         D
2022-01-01  0.558437 -2.143582 -1.044916 -0.420143
2022-01-02 -1.455120 -0.730625 -1.055827  0.937242
2022-01-03 -1.003578 -2.075778  1.121028 -0.910314
2022-01-04  1.016280  0.517562 -1.025515 -1.856076
2022-01-05  1.868480  2.037152  1.032562  0.190812
2022-01-06  0.896075  0.817188 -1.321133  0.107609
2022-01-07  1.253625 -0.693184 -0.701050  1.870586
2022-01-08 -0.772740  0.775458 -0.241953 -0.663553
2022-01-09 -1.131569  0.020151 -0.317010  1.026791
2022-01-10 -0.451815 -1.067281  0.424672 -1.080125
2022-01-11 -1.589348 -1.680571  2.029100 -0.041973
2022-01-12  1.132220  1.301167  1.154940  0.839083
2022-01-13  0.138459  0.004649  1.434378  2.624549
2022-01-14  0.296707  0.543502 -0.117240 -1.688556
2022-01-15 -0.935843 -1.419529 -0.482562 -0.786443
2022-01-16  0.308449 -0.335335 -1.451534  0.030591
2022-01-17  0.660346 -0.702253 -1.291539 -1.846197
2022-01-18  0.425913 -0.014023  1.150072 -1.976980
2022-01-19  1.574675  1.252467 -1.433446  2.205638
2022-01-20  0.613642  0.859947  0.551890  0.627359

In [39]:
data_frame3.to_numpy()

array([[1.0, Timestamp('2022-01-01 00:00:00'), 3.0, 3, 'girl', 'females'],
       [1.0, Timestamp('2022-01-02 00:00:00'), 3.0, 3, 'woman',
        'females'],
       [1.0, Timestamp('2022-01-03 00:00:00'), 3.0, 3, 'girl', 'females'],
       [1.0, Timestamp('2022-01-04 00:00:00'), 3.0, 3, 'woman',
        'females'],
       [1.0, Timestamp('2022-01-05 00:00:00'), 3.0, 3, 'girl', 'females']],
      dtype=object)

In [40]:
sample_data_frame.describe()

A          B          C          D
count  20.000000  20.000000  20.000000  20.000000
mean    0.170165  -0.136646  -0.079254  -0.040505
std     1.031026   1.172334   1.106061   1.360035
min    -1.589348  -2.143582  -1.451534  -1.976980
25%    -0.813516  -0.814789  -1.047644  -0.952767
50%     0.367181  -0.004687  -0.279481  -0.005691
75%     0.926126   0.785891   1.054679   0.863623
max     1.868480   2.037152   2.029100   2.624549

In [41]:
# Pandas DataFrame: transpose(); T is not callable
t = sample_data_frame.T
t

2022-01-01  2022-01-02  2022-01-03  2022-01-04  2022-01-05  2022-01-06  \
A    0.558437   -1.455120   -1.003578    1.016280    1.868480    0.896075   
B   -2.143582   -0.730625   -2.075778    0.517562    2.037152    0.817188   
C   -1.044916   -1.055827    1.121028   -1.025515    1.032562   -1.321133   
D   -0.420143    0.937242   -0.910314   -1.856076    0.190812    0.107609   

   2022-01-07  2022-01-08  2022-01-09  2022-01-10  2022-01-11  2022-01-12  \
A    1.253625   -0.772740   -1.131569   -0.451815   -1.589348    1.132220   
B   -0.693184    0.775458    0.020151   -1.067281   -1.680571    1.301167   
C   -0.701050   -0.241953   -0.317010    0.424672    2.029100    1.154940   
D    1.870586   -0.663553    1.026791   -1.080125   -0.041973    0.839083   

   2022-01-13  2022-01-14  2022-01-15  2022-01-16  2022-01-17  2022-01-18  \
A    0.138459    0.296707   -0.935843    0.308449    0.660346    0.425913   
B    0.004649    0.543502   -1.419529   -0.335335   -0.702253   -0.014023   
C    1.434378   -0.117240   -0.482562   -1.451534   -1.291539    1.150072   
D    2.624549   -1.688556   -0.786443    0.030591   -1.846197   -1.976980   

   2022-01-19  2022-01-20  
A    1.574675    0.613642  
B    1.252467    0.859947  
C   -1.433446    0.551890  
D    2.205638    0.627359

In [59]:
# sample_data_frame.sort_index(axis=0, ascending=False)
# sample_data_frame.sort_values(by="D", ascending=True)

sample_data_frame[0:4].sort_index(axis=1, ascending=True)


A         B         C         D
2022-01-01  0.558437 -2.143582 -1.044916 -0.420143
2022-01-02 -1.455120 -0.730625 -1.055827  0.937242
2022-01-03 -1.003578 -2.075778  1.121028 -0.910314
2022-01-04  1.016280  0.517562 -1.025515 -1.856076

### What is axis in pandas DataFrame?
![IMG](https://railsware.com/blog/wp-content/uploads/2018/11/data-frame-axes.png)

In [58]:
# sample_data_frame[0:4].sort_index(axis=0, ascending=True)

A         B         C         D
2022-01-01  0.558437 -2.143582 -1.044916 -0.420143
2022-01-02 -1.455120 -0.730625 -1.055827  0.937242
2022-01-03 -1.003578 -2.075778  1.121028 -0.910314
2022-01-04  1.016280  0.517562 -1.025515 -1.856076